server.port=8081
spring.application.name=user-service

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always